level5/app5/urls.py
from django.conf.urls import url
# from django.contrib import admin
from app5 import views
from django.urls import path, re_path

#TEMPLATE taggin
app_name = 'app5'

urlpatterns=[
    re_path(r'^user_login/$',views.user_login,name='user_login'),
    re_path(r'^register/$', views.register, name = 'register' ),
    re_path(r'^special/',views.special,name='special'),
]

level5/level5/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from app5 import views

urlpatterns = [
    re_path(r'^$', views.index, name='index'),
     
    path('admin/', admin.site.urls),
    re_path(r'^app5/', include('app5.urls')),
    re_path(r'^logout/$', views.user_logout, name='logout'),
]

level5/app5/models.py
from django.db import models
from django.contrib.auth.models import User

class UserProfileInfo(models.Model):

    user = models.OneToOneField(User, on_delete=models.CASCADE)

    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to="profile_pics", blank=True)

    def __str__(self):
        return self.user.username

# Create your models here.

level5/app5/forms.py
from django import forms
from django.contrib.auth.models import User
from app5.models import UserProfileInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username', 'email', 'password')

class UserProfileForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site','profile_pic')

level5/app5/views.py
from django.shortcuts import render
from app5.forms import UserForm, UserProfileForm

#the following are needed to effect user login
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required

def index(request):
    return render(request,'app5/index.html')

@login_required
def special(request):
    # Remember to also set login url in settings.py!
    # LOGIN_URL = '/basic_app/user_login/'
    return HttpResponse("You are logged in.")

@login_required
def user_logout(request):
    # Log out the user.
    logout(request)
    # Return to homepage.
    return HttpResponseRedirect(reverse('index'))

def register(request):

    registered = False

    if request.method == 'POST':

        # Get info from "both" forms
        # It appears as one form to the user on the .html page
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileForm(data=request.POST)

        # Check to see both forms are valid
        if user_form.is_valid() and profile_form.is_valid():
            
            # Save User Form to Database
            user = user_form.save()

            # Hash the password
            user.set_password(user.password)

            # Update with Hashed password
            user.save()

            # Now we deal with the extra info!

            # Can't commit yet because we still need to manipulate
            profile = profile_form.save(commit=False)

            # Set One to One relationship between
            # UserForm and UserProfileInfoForm
            profile.user = user

            # Check if they provided a profile picture
            if 'profile_pic' in request.FILES:
                print('found it')
                # If yes, then grab it from the POST form reply
                profile.profile_pic = request.FILES['profile_pic']

            # Now save model
            profile.save()

            # Registration Successful!
            registered = True

        else:
            # One of the forms was invalid if this else gets called.
            print(user_form.errors,profile_form.errors)

    else:
        # Was not an HTTP post so we just render the forms as blank.
        user_form = UserForm()
        profile_form = UserProfileForm()

    # This is the render and context dictionary to feed
    # back to the registration.html file page.
    return render(request,'app5/registration.html',
                          {'user_form':user_form,
                           'profile_form':profile_form,
                           'registered':registered})
   

def relative(request):
    return render(request, 'app5/relative.html')

def user_login(request):

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)

                return HttpResponseRedirect(reverse('index'))

            else:
                return HttpResponse("Your account is not active.")

        else:
            print("Someone tried to login and failed.")
            print("They used username: {} and password: {}".format(username,password))
            return HttpResponse("Invalid login details supplied.")

    else:
        #Nothing has been provided for username or password.
        print("last else fired")
        return render(request, 'app5/login.html', {})

level5/templates/app5/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="/static/master.css">
</head>
<body>
    <nav class="navbar navbar-default navbar-static-top">
        <div class = "container">
            <ul class="nav navbar-nav">

                <li class="navbar-brand"><a href="{% url 'index' %}">BRAND</a></li>
                <li class="navbar-link"><a href="{% url 'admin:index' %}">Admin</a></li>
                <li class="navbar-link"><a href="{% url 'app5:register' %}">Register</a></li>
                

                {% if user.is_authenticated %}
                <li><a class="navbar-link" href="{% url 'logout' %}">Logout</a></li>
                <li class="navbar-link"><a href="{% url 'app5:special' %}">Special</a></li>
                {% else %}
                <li><a class="navbar-link" href="{% url 'app5:user_login' %}">Login</a></li>
                {% endif %}

            </ul>
        </div>
    </nav>
    <div class="container">
        <div class="jumbotron">
        {% block body_block %}
        {% comment %} Anythin outside of this will be inherited {% endcomment %}
        {% endblock %}
    </div>
    </div>
    
</body>
</html>

level5/templates/app5/index.html
<!DOCTYPE html>
{% extends "app5/base.html" %}
{% comment %} {% load extras %} {% endcomment %}
    {% block body_block %}
        <h1>Django Level 5 Homepage</h1>
    {% endblock %}

level5/templates/app5/login.html
<!DOCTYPE html>
{% extends "app5/base.html" %}
{% comment %} {% load extras %} {% endcomment %}
    {% block body_block %}
        <h1>Login Page</h1>
        <form method="post" action="{% url 'app5:user_login' %}">
                {% csrf_token %}
                {# A more "HTML" way of creating the login form#}
                <label for="username">Username:</label>
                <input type="text" name="username" placeholder="Username">
      
                <label for="password"></label>
                <input type="password" name="password">
      
                <input type="submit" name="" value="Login">
      
              </form>

    {% endblock %}

level5/templates/app5/other.html
<!DOCTYPE html>
{% extends "app5/base.html" %}
    {% block body_block %}
        <h1>Other HTML</h1>
        <p>Example of template inheritance</p>
    {% endblock %}

level5/templates/app5/registration.html
<!DOCTYPE html>
{% extends "app5/base.html" %}
{% comment %} {{% load staticfiles %}} {% endcomment %}
{% comment %} {% load extras %} {% endcomment %}
    {% block body_block %}
        <h1>Registration Page</h1>

        {% if registered %}
            <p>Thanks for registering</p>

        {% else %}
         <h2>Register Here</h2>
         <h3>Fill out form</h3>

         <form enctype="multipart/form-data" method="POST">
          {% csrf_token %}
          {{ user_form.as_p }}
          {{ profile_form.as_p }}
          <input type="submit" value="Register">
        </form>
        {% endif %}
    {% endblock %}

level5/templates/app5/special.html
<!DOCTYPE html>
{% extends "app5/base.html" %}
    {% block body_block %}
        <h1>Special</h1>
        <p>You are logged in and can view the special content</p>
    {% endblock %}